name: Swift

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Swift 6.0
        uses: swift-actions/setup-swift@v2.2.0
        with:
          swift-version: "6.0"

      - name: Verify Swift version
        run: swift --version
      
      - name: Build & Test (macOS)
        run: swift test

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Swift 6.0
        uses: swift-actions/setup-swift@v2.2.0
        with:
          swift-version: "6.0"

      - name: Verify Swift version
        run: swift --version
      
      - name: Build & Test (Linux)
        run: swift test
        